### ISSUE TITLE
似乎沒有效果呢

### ISSUE THREAD

**Issue by bluelovers** [xiyuan-fengyu/IdeaPluginTypeScriptExecutor#2]
對著 .ts 按右鍵沒有出現 run 
有的檔案有 有的檔案沒有(大多數都沒有 只有少部分才出現)

**Comment by xiyuan-fengyu** [comment]
新的版本发布了， 试一下看看
https://github.com/xiyuan-fengyu/IdeaPluginTypeScriptExecutor/blob/master/release/IdeaPluginTypeScriptExecutor-1.0.2.jar

现在项目打开后就会立即编译一次 tsconfig.json 配置的rootDir 中的ts文件，只有能够在输出目录找到与原ts对应的js文件才会显示 Run / Debug 按钮

**Comment by bluelovers** [comment]
其實 要不要做成 run conf 形式(然後透過 ts-node)

也就是透過這各 run 的會出現在 run conf 底下的 typescript (ts-node) 然後執行

這樣一來就不需要去主動編譯 也不會造成編譯不需要的檔案的問題

**Comment by xiyuan-fengyu** [comment]
编译ts文件的功能是直接调用的idea 内置插件 JavaScriptLangulage 中的TypeScriptCompileService，这个服务在后台运行，它会监听ts文件变化，增量编译有变化的ts文件，并不需要主动去编译，也不会出现不必要的编译。这个插件实际执行的还是js文件，创建的执行配置也是js相关的，只是执行配置采用了原ts的文件名

**Comment by bluelovers** [comment]
那在這個基礎上建議在判斷檔案時
考慮一下 不存在 tsconfig 或者 沒設定 rootDir outDir 的狀況
因為實際上 .js 有被編譯出來
但卻沒被插件的偵測機制判斷到

---

另外想問一下 你是怎麼設定 SDK 編譯環境的
因為我想試著編譯 卻直接失敗

> Error:java: invalid source release: 9

不然就是

```
Error:(11, 44) java: package com.intellij.lang.javascript.service does not exist
Error:(14, 59) java: package com.intellij.lang.typescript.compiler.action.before does not exist
Error:(23, 32) java: package com.jetbrains.nodejs.run does not exist

....

```

**Comment by xiyuan-fengyu** [comment]
那在這個基礎上建議在判斷檔案時
考慮一下 不存在 tsconfig 或者 沒設定 rootDir outDir 的狀況
因為實際上 .js 有被編譯出來
但卻沒被插件的偵測機制判斷到

这些情况我之前也考虑过，但感觉没有找到合适的统一解决方案，所以暂时必须创建 tsconfig，并配置 rootDir，outDir


编译方式  
我的环境：JDK 1.8， IDEA 2018.1.2
clone这个项目后  
用IDEA 以clone后的目录创建新的plugin项目  
![clipboard](https://user-images.githubusercontent.com/5716772/41495708-de66e204-715f-11e8-893e-11006b347515.png)  
选择已经下载的项目目录  
![1](https://user-images.githubusercontent.com/5716772/41495732-79343d68-7160-11e8-9211-4c11d45294d2.png)

如果没有添加 IDEA SDK，可以new一个InterlliJ Platform Plugin SDK， 选择idea的安装目录  
为 IDEA SDK 添加 JavaScriptLanguage（内置） ， NodeJs（需要额外安装）依赖
![2](https://user-images.githubusercontent.com/5716772/41495773-8d7bad50-7161-11e8-91f1-02d80b586756.png)

**Comment by bluelovers** [comment]
我用複製貼上試著做了一個 ts-node 的 run conf

不過除了手動新增能執行以外 其他該有的功能通通都是失敗XD
https://github.com/bluelovers/idea-run-typescript/tree/master/src/io/plugin/tsnode/execution

而且設定還無法儲存....

**Comment by bluelovers** [comment]
稍微改了一下 
https://github.com/xiyuan-fengyu/IdeaPluginTypeScriptExecutor/pull/3

要是可以的話
希望能支援 只有 按下 RUN/Debug 之後 才會出現在 run conf 列表內

**Comment by xiyuan-fengyu** [comment]
整合好了，改进了一下，现在点击 Run / Debug 之后才添加 run conf 了

**Comment by bluelovers** [comment]
新版的 release 內的 jar 直接安裝似乎出錯 run/debug 按了沒反應

```
2018-06-18 23:37:15,309 [ 479834]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
	at com.xiyuan.ts.execution.NodeJsExecution.execute(NodeJsExecution.java:117)
	at com.xiyuan.ts.action.RunAction.actionPerformed(RunAction.java:18)
```

**Comment by xiyuan-fengyu** [comment]
我这里无法重现这个问题，你那边部署一下这个项目，看看是什么问题。我已经尝试性修复了一下

**Comment by bluelovers** [comment]
總算搞定了 ts-node run conf 版 lol
https://github.com/bluelovers/idea-run-typescript
