### ISSUE TITLE
插件会在idea启动时候编译所有ts文件,可以设置为可选吗?

### ISSUE THREAD

**Issue by JsonSong89** [xiyuan-fengyu/IdeaPluginTypeScriptExecutor#4]
首先谢谢作者的插件,在开发node.js项目时候很方便.
但有些前端项目,我是希望ts走webpack统一输出,ts实时编译我也是关掉的,但这个插件默认会在项目启动时编译一遍ts文件,可以设置为project级别的可选项吗?

**Comment by xiyuan-fengyu** [comment]
可以的，后面几天我把这个功能加上

**Comment by xiyuan-fengyu** [comment]
最新版的要过几天稳定了我再发布到idea plugin，暂时可以从下面的地址下载最新版 
 https://github.com/xiyuan-fengyu/IdeaPluginTypeScriptExecutor/blob/master/release/IdeaPluginTypeScriptExecutor-1.0.5.jar

**Comment by JsonSong89** [comment]
好的,我先测试下,多谢了.
